(******************************************************************************)
(*                                                                            *)
(*                    Apollo 11 Guidance Computer Software                    *)
(*                                                                            *)
(*     Operational semantics for Apollo 11 AGC mission programs: Luminary     *)
(*     099 for the LM and Comanche 055 for the CM. Executive scheduling,      *)
(*     alarms, restarts, DSKY interaction, and key guidance phase invariants. *)
(*                                                                            *)
(*     "There was no choice but to be pioneers."                              *)
(*     - Margaret Hamilton, 2009                                              *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 10, 2026                                                   *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
